superheroes/superhero/urls.py
from django.urls import path

from . import views

app_name = 'superhero'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete/<int:hero_id>/', views.delete, name='delete'),
    path('edit/<int:hero_id>/', views.edit, name='edit'),

]

superheroes/superheroes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superhero/', include('superhero.urls')),
    path('', RedirectView.as_view(url='/superhero/')),
    
]

superheroes/superhero/models.py
from django.db import models

# Create your models here.

class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superheroes/superhero/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero


# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes' : all_heroes
    }
    return render(request, 'superhero/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero' : single_hero
    }
    return render(request, 'superhero/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catchphrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superhero:index'))
    else:
        return render(request, 'superhero/create.html')

def delete(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    single_hero.delete()
    return HttpResponseRedirect(reverse('superhero:index'))

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        single_hero.name = request.POST.get('name')
        single_hero.alter_ego = request.POST.get('alter_ego')
        single_hero.primary = request.POST.get('primary')
        single_hero.secondary = request.POST.get('secondary')
        single_hero.catchphrase = request.POST.get('catchphrase')
        single_hero.save()
        return HttpResponseRedirect(reverse('superhero:index'))
    else:
        context = {
        'single_hero' : single_hero
    }
        return render(request, 'superhero/edit.html', context)

superheroes/superhero/templates/superhero/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superhero:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
    <a href="{% url 'superhero:index' %}">Homepage</a>
</body>
</html>

superheroes/superhero/templates/superhero/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hero Details</title>
</head>
<body>
    <h1>{{single_hero.name}}</h1>
    <ul>
        <li> <h2>Alter ego: {{single_hero.alter_ego}}</h2> </li>
        <li> <h2>Primary Ability: {{single_hero.primary_ability}}</h2> </li>
        <li> <h2>Secondary Ability: {{single_hero.secondary_ability}}</h2> </li>
        <li> <h2>Catchphrase: {{single_hero.catchphrase}}</h2> </li>
    </ul>
    <a href="{% url 'superhero:index' %}">Homepage</a>
</body>
</html>

superheroes/superhero/templates/superhero/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero Details</title>
</head>
<body>
    <form action="{% url 'superhero:edit' single_hero.id %}" method="post">
        {% csrf_token %} 
        Name: <input type="text" name="name" id="name" value="{{single_hero.name}}"><br />
        Alter ego: <input type="text" name="alter_ego" id="alter_ego" value="{{single_hero.alter_ego}}"><br />
        Primary Ability:  <input type="text" name="primary" id="primary" value="{{single_hero.primary_ability}}"><br />
        Secondary Ability:  <input type="text" name="secondary" id="secondary" value="{{single_hero.secondary_ability}}"><br />
        Catchphrase:  <input type="text" name="catchphrase" id="catchphrase" value="{{single_hero.catchphrase}}"><br />
        <input type="submit" value="Change Detail(s)!">
    </form>
    <a href="{% url 'superhero:index' %}">Homepage</a>
</body>
</html>

superheroes/superhero/templates/superhero/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    {% load static %}
    <img src="{% static 'yulia-matvienko-kgz9vsP5JCU-unsplash.jpg' %}" alt="Batman and Superman legos." style="max-width: 25%; height:auto">
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li> <h2>{{hero.name}} - <a href="{% url 'superhero:detail' hero.id %}"> Click for details</a> 
            <a href="{% url 'superhero:edit' hero.id %}">Edit Hero Details</a>
            <a href="{% url 'superhero:delete' hero.id %}">Delete Hero</a></h2> </li>
        {% endfor %}
    </ul>
    <a href="{% url 'superhero:create' %}">Add New Hero</a>

</body>
</html>